name = "campusflow-server"
compatibility_date = "2024-03-03"

[vars]
ALLOWED_ORIGINS = "https://campusflowapp.pages.dev/"
# Add global environment variables if needed

[[d1_databases]]
binding = "DB"
database_name = "campusflow-db"
database_id = "810ea872-2b35-42a6-8801-1f4cfab1d2c1" # Local and remote fallback UUID

[[r2_buckets]]
binding = "campusflow_bucket"
bucket_name = "campusflow-bucket"

[[vectorize]]
binding = "VECTORIZE"
index_name = "campusflow-index"
