import { writeFileSync } from 'fs';
import { join } from 'path';

async function seed() {
  console.log('🌱 Starting D1 Database Seeding...');

  // Mock Students
  const students = [
    {
      id: 'usr-stud-1',
      name: 'Aaron Jibz',
      email: 'aaron@campusflow.edu',
      branch: 'CSE',
      semester: 6,
    },
    {
      id: 'usr-stud-2',
      name: 'Emily Watson',
      email: 'emily@campusflow.edu',
      branch: 'ECE',
      semester: 4,
    },
    { id: 'usr-stud-3', name: 'Raj Patel', email: 'raj@campusflow.edu', branch: 'ME', semester: 8 },
    {
      id: 'usr-stud-4',
      name: 'Sofia Rodriguez',
      email: 'sofia@campusflow.edu',
      branch: 'EE',
      semester: 2,
    },
    {
      id: 'usr-stud-5',
      name: 'Liam Chen',
      email: 'liam@campusflow.edu',
      branch: 'CSE',
      semester: 6,
    },
  ];

  const defaultPassword = 'password123';
  const sqlStatements: string[] = [
    '-- Seeding script generated by server/seed.ts',
    'PRAGMA foreign_keys = ON;',
    'DELETE FROM placement_attempts;',
    'DELETE FROM deadlines;',
    'DELETE FROM attendance;',
    'DELETE FROM tasks;',
    'DELETE FROM users;',
  ];

  console.log('🔑 Hashing student passwords...');
  for (const s of students) {
    const passwordHash = await Bun.password.hash(defaultPassword, { algorithm: 'bcrypt' });
    const goals = JSON.stringify([
      'Maintain 8.5+ CGPA',
      'Prepare for Placements',
      'Publish Research Paper',
    ]);

    sqlStatements.push(
      `INSERT INTO users (id, email, password_hash, name, role, branch, semester, attendance_target, academic_goals) VALUES ('${s.id}', '${s.email}', '${passwordHash}', '${s.name}', 'student', '${s.branch}', ${s.semester}, 75.0, '${goals.replace(/'/g, "''")}');`,
    );
  }

  // Mock Attendance (10 dummy records)
  // Let's assign attendance records to students
  const attendanceMock = [
    { userId: 'usr-stud-1', subject: 'Data Structures & Algorithms', attended: 24, total: 30 },
    { userId: 'usr-stud-1', subject: 'Database Management Systems', attended: 18, total: 20 },
    { userId: 'usr-stud-1', subject: 'Operating Systems', attended: 12, total: 20 },
    { userId: 'usr-stud-2', subject: 'Signals & Systems', attended: 15, total: 22 },
    { userId: 'usr-stud-2', subject: 'Microprocessors', attended: 20, total: 20 },
    { userId: 'usr-stud-3', subject: 'Thermodynamics', attended: 16, total: 25 },
    { userId: 'usr-stud-3', subject: 'Fluid Mechanics', attended: 22, total: 24 },
    { userId: 'usr-stud-4', subject: 'Basic Electrical Eng', attended: 18, total: 28 },
    { userId: 'usr-stud-5', subject: 'Compiler Design', attended: 25, total: 30 },
    { userId: 'usr-stud-5', subject: 'Computer Networks', attended: 14, total: 22 },
  ];

  console.log('📝 Generating attendance records...');
  attendanceMock.forEach((att, idx) => {
    const id = `att-${idx + 1}`;
    sqlStatements.push(
      `INSERT INTO attendance (id, user_id, subject_name, attended, total, target_percentage) VALUES ('${id}', '${att.userId}', '${att.subject}', ${att.attended}, ${att.total}, 75.0);`,
    );
  });

  // Mock Deadlines (10 dummy records)
  const deadlinesMock = [
    {
      userId: 'usr-stud-1',
      title: 'DSA Assignment 3',
      desc: 'Binary search trees and AVL trees',
      due: '2026-07-02',
    },
    {
      userId: 'usr-stud-1',
      title: 'DBMS Course Project',
      desc: 'Final project report submission',
      due: '2026-07-10',
    },
    {
      userId: 'usr-stud-2',
      title: 'Signals Lab Report',
      desc: 'Fourier transform lab exercises',
      due: '2026-06-30',
    },
    {
      userId: 'usr-stud-2',
      title: 'Microprocessors Quiz',
      desc: 'Chapter 1 to 4 multi-choice quiz',
      due: '2026-07-05',
    },
    {
      userId: 'usr-stud-3',
      title: 'CAD Modeling Submission',
      desc: 'Gearbox 3D model project',
      due: '2026-07-15',
    },
    {
      userId: 'usr-stud-3',
      title: 'Fluid Dynamics Quiz',
      desc: 'Bernoullis theorem concepts test',
      due: '2026-06-29',
    },
    {
      userId: 'usr-stud-4',
      title: 'Electrical Circuit Lab',
      desc: 'Kirchoffs laws experiments file',
      due: '2026-07-01',
    },
    {
      userId: 'usr-stud-5',
      title: 'Compiler Design Lab',
      desc: 'Lexical analyzer flex program',
      due: '2026-07-03',
    },
    {
      userId: 'usr-stud-5',
      title: 'CN Quiz 2',
      desc: 'IP addressing & routing protocols',
      due: '2026-07-08',
    },
    {
      userId: 'usr-stud-1',
      title: 'OS Lab Examination',
      desc: 'Process synchronization code test',
      due: '2026-07-12',
    },
  ];

  console.log('📝 Generating deadline records...');
  deadlinesMock.forEach((dl, idx) => {
    const id = `dl-${idx + 1}`;
    sqlStatements.push(
      `INSERT INTO deadlines (id, user_id, title, description, due_date, status) VALUES ('${id}', '${dl.userId}', '${dl.title.replace(/'/g, "''")}', '${dl.desc.replace(/'/g, "''")}', '${dl.due}', 'pending');`,
    );
  });

  // Write to server/seed.sql
  const outPath = join(__dirname, 'seed.sql');
  writeFileSync(outPath, sqlStatements.join('\n'), 'utf8');
  console.log(`✅ SQL seed commands written to ${outPath}`);

  console.log('⚡ Executing schema and seed SQL in local D1 database using Wrangler...');

  // Create / Run SQLite database migrations/schema in D1 Local
  const schemaPath = join(__dirname, 'schema.sql');

  console.log('1. Executing Schema...');
  const schemaProcess = Bun.spawnSync([
    'bunx',
    'wrangler',
    'd1',
    'execute',
    'DB',
    '--local',
    `--file=${schemaPath}`,
  ]);

  if (schemaProcess.exitCode !== 0) {
    console.error('❌ Failed to execute schema in local D1 database:');
    console.error(schemaProcess.stderr.toString());
    process.exit(1);
  }
  console.log(schemaProcess.stdout.toString());

  console.log('2. Executing Seed...');
  const seedProcess = Bun.spawnSync([
    'bunx',
    'wrangler',
    'd1',
    'execute',
    'DB',
    '--local',
    `--file=${outPath}`,
  ]);

  if (seedProcess.exitCode !== 0) {
    console.error('❌ Failed to execute seed in local D1 database:');
    console.error(seedProcess.stderr.toString());
    process.exit(1);
  }
  console.log(seedProcess.stdout.toString());

  console.log('🎉 Seeding successfully completed!');
}

seed().catch(console.error);
